services:
  - type: web
    name: ambulance-server
    env: node
    buildCommand: yarn install && cd frontend && yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health
